name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v6
        with:
          stale-issue-message: 'This issue has been open 5 days with no activity. Remove stale label or comment or it will be closed in 2 days.'
          days-before-stale: 5
          days-before-close: 2
          close-issue-reason: completed
          stale-issue-label: DONE ACTIONING
